### ISSUE TITLE
[Bug] Encountering error in Non Chromium browser test

### ISSUE THREAD

**Issue by yj-ang** [bgotink/playwright-coverage#17]
Hi, thanks for developing this handy package!

I'm new to Playwright toolsets. Currently, I have my Playwright test cases running in all browser variants with the following dependencies:
- `playwright@1.32.3`, 
- `@playwright/test@1.32.2` 
- `@bgotink/playwright-coverage@0.2.0`

But I'm getting this error in non Chromium browser.

```
 1) [firefox] › xxxx/xxx.e2e.ts:6:5 › <test-case-name>

    TypeError: coverage.startJSCoverage: Cannot read properties of null (reading 'startJSCoverage')

        at Object.page (/xxxx/node_modules/@bgotink/playwright-coverage/src/fixtures.ts:31:7)
```

I figure out that `page.coverage.startJSCoverage` object is never a null value in Non Chromium test. For now, I'm bypassing the error by patch the package with the following replacement. Not sure if it's the best way to resolve the error. If it's, I would love to help on submitting a pull request for the fix.

```
diff --git a/node_modules/@bgotink/playwright-coverage/lib/fixtures.js b/node_modules/@bgotink/playwright-coverage/lib/fixtures.js
index 2c957bd..8a31072 100644
--- a/node_modules/@bgotink/playwright-coverage/lib/fixtures.js
+++ b/node_modules/@bgotink/playwright-coverage/lib/fixtures.js
@@ -6,7 +6,7 @@ const data_1 = require("./data");
 const coverageFixtures = {
     collectCoverage: true,
     page: async ({ page, collectCoverage }, use, testInfo) => {
-        if (page.coverage == null || !collectCoverage) {
+        if (page.coverage == null || !collectCoverage || testInfo.project.use.defaultBrowserType !== 'chromium') {
             return use(page);
         }
         await page.coverage.startJSCoverage({

```

**Comment by bgotink** [comment]
This is a very weird error. The error says `page.coverage` is null so it can't read the `startJSCoverage` function from it, but the line above explicitly checks for `page.coverage == null` and even logging the function works just fine&hellip;

I've fixed it by basically applying your patch but using the `browserName` fixture instead of the `testInfo`. Going through the fixture should be a bit more robust given the number of ways the browser could be configured (defaultBrowserType, browserName, in a project, in `test.use()`, in `test.extend()`).

Could you try again using version 0.2.1?
