### ISSUE TITLE
Which sourcemaps work?

### ISSUE THREAD

**Issue by Zache** [bgotink/playwright-coverage#3]
We have inline sourcemaps, and that didn't work. I tried some other option but while it generated a report, that report contained 0 coverage information.

**Comment by bgotink** [comment]
I've only tested this on one angular application that used separate sourcemap files, the `data:` URLs used for inline source maps weren't supported yet.

Could you retry with version 0.1.1? That should support inline source maps.

I should probably look into adding some tests to this repository, with small angular/react/vue/webpack/... apps to run those tests on.

**Comment by Zache** [comment]
I tried with 0.1.1 and eval-source-map which uses data urls. It didn't crash, but neither did I get anything in my coverage report. It still worked with source-map but something is wrong with the html reports generated for individual files. 

They only contain an error like this:

Error: Failed to read \src\<my repo>\<my repo>\src\<path to file>.ts: Error: ENOENT: no such file or directory, open 'C: \src\<my repo>\<my repo>\src\<path to file>.ts'

I probably messed something up, since the file path starts with \<where i keep my repos>\<my repo>\<my repo AGAIN>\<the rest of the path with is correct> but I've yet to fix it

Also I'm 99% sure that the included exclude patterns don't work on windows because / is the wrong path separator there

**Comment by bgotink** [comment]
The exclude paths are applied on URL paths rather than regular file paths, so they should always use `/` regardless of the operating system's path separator. I'm not sure what file URLs look like on Windows, but I assume it looks like `file://<something to denote what drive the file is on>/path/to/the/file`. The exclusions are executed on the `pathname` part of such a file URL.

I've opted for URLs there because some setups make the sourcemaps available over HTTP. That's what the angular CLI outputs if you serve the application, for example.

Istanbul, which is used to generate the actual reports themselves, only requires the actual source content to generate the HTML reports. If it can't read the file (e.g. because of an invalid path) it prints the error it encountered into the HTML report rather than failing the report generation.
I don't think there's anything I can configure to change that.

**Comment by Zache** [comment]
Thank you for your reply, I should have been more specific. I meant your default excluded patterns for node_modules and webpack. I managed to exclude node_modules with my own pattern (`**/node_modules/**`), but webpack was more stubborn, but it comes on the bottom of the html report and so isn't as distracting.

I found my problem with the paths containing the repository root folder two times, it came from the default `devtoolModuleFilenameTemplate` and was causing trouble inside of v8-to-istanbul when it tried to resolve paths. I changed it to be only `webpack://[resource-path]` and that fixed it for me.

I still can only get it to work with `devtool: source-map` but that's not a big problem. Thank you for a great library
