### ISSUE TITLE
Add an option to rewrite paths

### ISSUE THREAD

**Issue by JCMais** [bgotink/playwright-coverage#4]
Hi, this is an awesome library!

I was trying to use it with one my projects, but all the paths have the webpack prefix `_N_E` on them, making it not work correctly:

![image](https://user-images.githubusercontent.com/1041647/148461469-7f6433a4-6f17-43ee-a4ce-5041aa27feac.png)

![image](https://user-images.githubusercontent.com/1041647/148461657-0487e02b-6069-4b29-aa06-d73002d3bc02.png)

If I had a way to rewrite those paths, I would be able to fix this issue.

**Comment by bgotink** [comment]
Looks like that's an extra prefix Next.js adds to webpack, I'll take a look at stripping that.

In one of your screenshots there's a file `e2e/_N_E/design/src/index.ts`. Is the actual file located at `design/src/index.ts` or at `e2e/design/src/index.ts`?
I can't seem to find documentation on the `_N_E` prefix and I don't use next.js myself, so I can't tell.

> If I had a way to rewrite those paths, I would be able to fix this issue.

That would be helpful in case other tools have similar settings, to prevent this library from having to manage all possible cases.
There's one problem though: the code that's mapping the paths runs inside a worker. In other words, having this function as a configuration property would either require a lot of communication between main thread and worker (seriously slowing down the entire process) or it would seriously limit the functionality supported in this function (only functions that don't use any variables from an outer scope could be "sent" to the worker in order to run there).

**Comment by JCMais** [comment]
Thanks for looking at this! Yes, I am using Next.js.

This is a monorepo, the e2e tests are inside `<root>/packages/e2e/`  and the other file is inside `<root>/packages/design/src/index.ts`.

**Comment by bgotink** [comment]
I've finally realised that rewriting the paths can happen in the main thread, thereby removing all constraints that would be incurred when the rewriting would happen in the worker.

Version 0.1.2 has a `rewritePaths` option that gives you complete control over the path.

**Comment by tannerbaum** [comment]
For anyone who finds this issue, using the rewritePaths option in this way seems to have everything working for me. 

```ts
rewritePath: ({ relativePath }: { relativePath: string }) => {
	// not possible to use relative paths with the standard NextJS regex replacements below
	// if they makeup the entirety of the file, i.e _N_E/?1d62. Not sure what these files do yet.
	if (/^_N_E\/\?.*$/.test(relativePath)) {
		return relativePath;
	}

	// remove next file prefix and suffix
	return relativePath
		.replace("_N_E/", "")
		.replace(/\?.*/, "");
},
```

**Comment by KHisir** [comment]
Hello JCMais,

how did you get the framework to read your e2e folder. I use the framework with Angular and Plywright. With Playwright the e2e tests are in the tests folder by default. But unfortunately I can't get this folder to be read. Can you show me your playwright.config.ts file? This is my current result.

![image](https://github.com/bgotink/playwright-coverage/assets/13102380/1ca107da-166b-43a8-9685-38fde0430fc1)
